# Generated by Django 2.2.2 on 2021-11-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fabla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hide_reason',
            field=models.TextField(blank=True, verbose_name='伏字化理由'),
        ),
    ]
